Use time_t instead of long for variables passed to time().
Fixes FTBFS with 64-bit time_t:
```
../asyncsvr.c: In function ‘gltpd_svc_run’:
../asyncsvr.c:553:14: error: passing argument 1 of ‘time’ from incompatible pointer type [-Wincompatible-pointer-types]
  553 |         time(&currenttime);
      |              ^~~~~~~~~~~~
      |              |
      |              long int *
In file included from /usr/include/features.h:510,
                 from /usr/include/powerpc-linux-gnu/sys/types.h:25,
                 from /usr/include/tirpc/rpc/types.h:41,
                 from /usr/include/tirpc/rpc/rpc.h:38,
                 from /<<PKGBUILDDIR>>/ogdi/include/ecs.h:9,
                 from ../asyncsvr.c:51:
/usr/include/time.h:85:15: note: expected ‘time_t *’ {aka ‘long long int *’} but argument is of type ‘long int *’
   85 | extern time_t __REDIRECT_NTH (time, (time_t *__timer), __time64);
      |               ^~~~~~~~~~~~~~
../asyncsvr.c:574:12: error: passing argument 1 of ‘time’ from incompatible pointer type [-Wincompatible-pointer-types]
  574 |       time(&timecount);
      |            ^~~~~~~~~~
      |            |
      |            long int *
/usr/include/time.h:85:15: note: expected ‘time_t *’ {aka ‘long long int *’} but argument is of type ‘long int *’
   85 | extern time_t __REDIRECT_NTH (time, (time_t *__timer), __time64);
      |               ^~~~~~~~~~~~~~
```